apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    homelab/env: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    homelab/env: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    homelab/env: production
