apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  annotations:
    # Image Updater — vigila solo mi-cv-web (imagen propia)
    argocd-image-updater.argoproj.io/image-list: mi-cv-web=ghcr.io/marcosoto1321/mi-cv-web
    argocd-image-updater.argoproj.io/mi-cv-web.update-strategy: digest
    argocd-image-updater.argoproj.io/mi-cv-web.pull-secret: secret:argocd/argocd-image-updater-secret#git.token
    # Write-back a Git (GitOps correcto)
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-secret#git.token
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      exclude: '{**/*.example.yaml,**/values.yaml}'
      recurse: true
    path: k8s/apps
    repoURL: https://github.com/MarcoSoto1321/homelab-k8s
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
