apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2026-06-06T04:09:25Z"
  generation: 70
  name: core
  namespace: argocd
  resourceVersion: "13751"
  uid: f39b1685-d3cb-42fe-8b8c-3f943ae78d0b
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      exclude: '{**/*.example.yaml,**/values.yaml}'
      recurse: true
    path: k8s/core
    repoURL: https://github.com/MarcoSoto1321/homelab-k8s
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
status:
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2026-06-06T05:28:52Z"
    status: Healthy
  history:
  - deployStartedAt: "2026-06-06T04:09:25Z"
    deployedAt: "2026-06-06T04:14:36Z"
    id: 0
    initiatedBy:
      automated: true
    revision: 439f98868fb0b1d06ad537311d61929054ca3d97
    source:
      path: k8s/core
      repoURL: https://github.com/MarcoSoto1321/homelab-k8s
      targetRevision: HEAD
  - deployStartedAt: "2026-06-06T05:14:52Z"
    deployedAt: "2026-06-06T05:14:52Z"
    id: 1
    initiatedBy:
      automated: true
    revision: cbec7853dd8013a40ad3d3eec69109451c8b1f23
    source:
      path: k8s/core
      repoURL: https://github.com/MarcoSoto1321/homelab-k8s
      targetRevision: HEAD
  operationState:
    finishedAt: "2026-06-06T05:14:52Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        revision: cbec7853dd8013a40ad3d3eec69109451c8b1f23
        source:
          path: k8s/core
          repoURL: https://github.com/MarcoSoto1321/homelab-k8s
          targetRevision: HEAD
    phase: Succeeded
    startedAt: "2026-06-06T05:14:52Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Namespace
        message: namespace/apps unchanged
        name: apps
        namespace: kube-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Namespace
        message: namespace/infra unchanged
        name: infra
        namespace: kube-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Namespace
        message: namespace/monitoring unchanged
        name: monitoring
        namespace: kube-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: storage.k8s.io
        hookPhase: Running
        kind: StorageClass
        message: storageclass.storage.k8s.io/local-path unchanged
        name: local-path
        namespace: kube-system
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/argocd-ingress configured
        name: argocd-ingress
        namespace: argocd
        status: Synced
        syncPhase: Sync
        version: v1
      revision: cbec7853dd8013a40ad3d3eec69109451c8b1f23
      source:
        path: k8s/core
        repoURL: https://github.com/MarcoSoto1321/homelab-k8s
        targetRevision: HEAD
  reconciledAt: "2026-06-06T05:53:49Z"
  resourceHealthSource: appTree
  resources:
  - kind: Namespace
    name: apps
    status: Synced
    version: v1
  - kind: Namespace
    name: infra
    status: Synced
    version: v1
  - kind: Namespace
    name: monitoring
    status: Synced
    version: v1
  - group: networking.k8s.io
    kind: Ingress
    name: argocd-ingress
    namespace: argocd
    status: Synced
    version: v1
  - group: storage.k8s.io
    kind: StorageClass
    name: local-path
    status: Synced
    version: v1
  sourceHydrator: {}
  sourceType: Directory
  summary:
    externalURLs:
    - http://argocd.marco-sr.duckdns.org/
  sync:
    comparedTo:
      destination:
        namespace: kube-system
        server: https://kubernetes.default.svc
      source:
        directory:
          exclude: '{**/*.example.yaml,**/values.yaml}'
          recurse: true
        path: k8s/core
        repoURL: https://github.com/MarcoSoto1321/homelab-k8s
        targetRevision: HEAD
    revision: cbec7853dd8013a40ad3d3eec69109451c8b1f23
    status: Synced
