apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mi-cv-web
  namespace: argocd
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: false
    path: k8s/apps/mi-cv-web
    repoURL: https://github.com/MarcoSoto1321/homelab-k8s
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
