apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2026-06-06T04:08:36Z"
  generation: 50
  name: monitoring
  namespace: argocd
  resourceVersion: "13781"
  uid: 4a96f0d0-1c3a-4576-913e-46269cc162ae
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      exclude: '{**/*.example.yaml,**/values.yaml}'
      recurse: true
    path: k8s/monitoring
    repoURL: https://github.com/MarcoSoto1321/homelab-k8s
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
status:
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2026-06-06T04:08:36Z"
    status: Healthy
  history:
  - deployStartedAt: "2026-06-06T05:35:24Z"
    deployedAt: "2026-06-06T05:35:26Z"
    id: 0
    initiatedBy:
      automated: true
    revision: cbec7853dd8013a40ad3d3eec69109451c8b1f23
    source:
      directory:
        recurse: true
      path: k8s/monitoring
      repoURL: https://github.com/MarcoSoto1321/homelab-k8s
      targetRevision: HEAD
  operationState:
    finishedAt: "2026-06-06T05:35:26Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        revision: cbec7853dd8013a40ad3d3eec69109451c8b1f23
        source:
          directory:
            recurse: true
          path: k8s/monitoring
          repoURL: https://github.com/MarcoSoto1321/homelab-k8s
          targetRevision: HEAD
    phase: Succeeded
    startedAt: "2026-06-06T05:35:24Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: ServiceAccount
        message: serviceaccount/promtail configured
        name: promtail
        namespace: monitoring
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/loki-config configured
        name: loki-config
        namespace: monitoring
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/promtail-config configured
        name: promtail-config
        namespace: monitoring
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: PersistentVolumeClaim
        message: persistentvolumeclaim/loki-pvc configured
        name: loki-pvc
        namespace: monitoring
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRole
        message: clusterrole.rbac.authorization.k8s.io/promtail reconciled. reconciliation
          required update. clusterrole.rbac.authorization.k8s.io/promtail configured
        name: promtail
        namespace: monitoring
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRoleBinding
        message: clusterrolebinding.rbac.authorization.k8s.io/promtail reconciled.
          reconciliation required update. clusterrolebinding.rbac.authorization.k8s.io/promtail
          configured
        name: promtail
        namespace: monitoring
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/loki configured
        name: loki
        namespace: monitoring
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        images:
        - grafana/promtail:3.3.2
        kind: DaemonSet
        message: daemonset.apps/promtail configured
        name: promtail
        namespace: monitoring
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        images:
        - grafana/loki:3.3.2
        kind: Deployment
        message: deployment.apps/loki configured
        name: loki
        namespace: monitoring
        status: Synced
        syncPhase: Sync
        version: v1
      revision: cbec7853dd8013a40ad3d3eec69109451c8b1f23
      source:
        directory:
          recurse: true
        path: k8s/monitoring
        repoURL: https://github.com/MarcoSoto1321/homelab-k8s
        targetRevision: HEAD
  reconciledAt: "2026-06-06T05:54:12Z"
  resourceHealthSource: appTree
  resources:
  - kind: ConfigMap
    name: loki-config
    namespace: monitoring
    status: Synced
    version: v1
  - kind: ConfigMap
    name: promtail-config
    namespace: monitoring
    status: Synced
    version: v1
  - kind: PersistentVolumeClaim
    name: loki-pvc
    namespace: monitoring
    status: Synced
    version: v1
  - kind: Service
    name: loki
    namespace: monitoring
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: promtail
    namespace: monitoring
    status: Synced
    version: v1
  - group: apps
    kind: DaemonSet
    name: promtail
    namespace: monitoring
    status: Synced
    version: v1
  - group: apps
    kind: Deployment
    name: loki
    namespace: monitoring
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: promtail
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: promtail
    status: Synced
    version: v1
  sourceHydrator: {}
  sourceType: Directory
  summary:
    images:
    - grafana/loki:3.3.2
    - grafana/promtail:3.3.2
  sync:
    comparedTo:
      destination:
        namespace: monitoring
        server: https://kubernetes.default.svc
      source:
        directory:
          exclude: '{**/*.example.yaml,**/values.yaml}'
          recurse: true
        path: k8s/monitoring
        repoURL: https://github.com/MarcoSoto1321/homelab-k8s
        targetRevision: HEAD
    revision: cbec7853dd8013a40ad3d3eec69109451c8b1f23
    status: Synced
