apiVersion: v1
kind: Secret
metadata:
  name: firefly-secret
  namespace: apps
type: Opaque
stringData:
  APP_KEY: "base64:CHANGE_ME_32_bytes"     # echo "base64:$(openssl rand -base64 32)"
  DB_PASSWORD: "CHANGE_ME"                  # openssl rand -hex 16
  STATIC_CRON_TOKEN: "CHANGE_ME"            # openssl rand -hex 32
