apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: marcosoto-dev-wildcard
  namespace: infra # debe estar en el mismo namespace donde Traefik busca el Secret
spec:
  secretName: marcosoto-dev-tls # nombre del Secret que se crea con el certificado
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "apps,argocd,monitoring"
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "marcosoto.dev" # dominio raíz
    - "*.marcosoto.dev" # wildcard — cubre vault.marcosoto.dev, n8n.marcosoto.dev, etc.
