apiVersion: v1
kind: Service
metadata:
  name: firefly-importer-svc
  namespace: apps
spec:
  selector:
    app: firefly-importer
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firefly-importer-ingress
  namespace: apps
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik
  rules:
    - host: firefly-importer.marcosoto.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: firefly-importer-svc
                port:
                  number: 80
  tls:
    - hosts:
        - firefly-importer.marcosoto.dev
