apiVersion: v1
kind: Service
metadata:
  name: mi-cv-web-svc
  namespace: apps
  labels:
    app: mi-cv-web
spec:
  selector:
    app: mi-cv-web
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mi-cv-web-ingress
  namespace: apps
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - secretName: marcosoto-dev-tls
      hosts:
        - cv.marcosoto.dev
  rules:
    - host: cv.marcosoto.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mi-cv-web-svc
                port:
                  number: 80
