apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  namespace: apps
  labels:
    app: bookstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bookstack
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Esperando MariaDB..."
              until nc -z bookstack-db-svc 3306; do
                sleep 2
              done
              echo "MariaDB lista"
      containers:
        - name: bookstack
          image: lscr.io/linuxserver/bookstack:latest
          ports:
            - containerPort: 80
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: APP_URL
              value: "https://bookstack.marco-sr.duckdns.org"
            - name: DB_HOST
              value: "bookstack-db-svc"
            - name: DB_DATABASE
              value: "bookstackapp"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: bookstack-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: bookstack-secret
                  key: DB_PASS
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: bookstack-secret
                  key: APP_KEY
          volumeMounts:
            - name: data
              mountPath: /config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bookstack-pvc
