apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-pvc
  namespace: apps
  labels:
    app: bookstack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-db-pvc
  namespace: apps
  labels:
    app: bookstack-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
