apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: infra
  labels:
    app: cloudflare-ddns
    instance: wildcard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
      instance: wildcard
  template:
    metadata:
      labels:
        app: cloudflare-ddns
        instance: wildcard
    spec:
      containers:
        - name: cloudflare-ddns
          image: favonia/cloudflare-ddns:latest
          imagePullPolicy: Always
          env:
            - name: CLOUDFLARE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-ddns-token
                  key: api-token
            - name: DOMAINS
              value: "marcosoto.dev,*.marcosoto.dev"
            - name: PROXIED
              value: "false"
            - name: RECORD_COMMENT
              value: "managed-by-ddns-wildcard"
            - name: MANAGED_RECORDS_COMMENT_REGEX
              value: "^managed-by-ddns-wildcard$"
            - name: CACHE_EXPIRATION
              value: "5m"
            - name: UPDATE_CRON
              value: "*/5 * * * *"
            - name: IP6_PROVIDER
              value: "none"
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 250Mi
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      restartPolicy: Always
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
